flaskblog/post/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,SubmitField,TextAreaField
from wtforms.validators import DataRequired


class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content',validators=[DataRequired()])
    submit = SubmitField('Post')

flaskblog/post/routes.py
from flask import render_template,url_for,flash,redirect,request,abort,Blueprint
from functools import wraps
from Utils.ConfigReader import getInstance
from Utils.DBConnectivity import DBConnectivity
from flaskblog.post.forms import PostForm
from flaskblog import session

posts = Blueprint('posts',__name__)

#check User logged in or not
def is_logged_in(f):
    @wraps(f)
    def wrap(*args, **kwargs):
        if 'logged_in' in session:
            return f(*args,**kwargs)
        else:
            flash("Unauthorized, Please Login", "danger")
            return redirect(url_for("users.login"))      
    return wrap

#check User logged off or not
def is_logged_off(f):
    @wraps(f)
    def wrap(*args, **kwargs):
        if 'logged_in' not in session:
            return f(*args,**kwargs)
        else:
            flash("Unauthorized, Please Logout", "danger")
            return redirect(url_for("main.home"))      
    return wrap

@posts.route("/post/new",methods=['GET','POST'])
@is_logged_in
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        reader = getInstance()
        con = DBConnectivity.getConnection(reader.get('Credential', 'hostname'), reader.get('Credential', 'username'), reader.get('Credential', 'passwrod'), reader.get('Credential', 'database'))
        query = "select * from user where username='"+session['username']+"'"
        user = DBConnectivity.getQueryResult(con, query).fetchone()
        query = "insert into posts(title,content,user_id) values('"+form.title.data+"','"+form.content.data+"',"+str(user[0])+")"
        print(query)
        DBConnectivity.updateDatabase(con, query)
        flash('Your post has been created!','success')
        return redirect(url_for('main.home'))
    return render_template('create_post.html',title='New Post',legend="New Post",form=form)


@posts.route("/post/<int:post_id>",methods=['GET','POST'])
def post(post_id):
    reader = getInstance()
    con = DBConnectivity.getConnection(reader.get('Credential', 'hostname'), reader.get('Credential', 'username'), reader.get('Credential', 'passwrod'), reader.get('Credential', 'database'))
    query = "select u.user_id,u.username,u.image_file,p.post_id,p.title,p.content,p.date_posted from user u join posts p on u.user_id=p.user_id where post_id="+str(post_id)
    post = DBConnectivity.getQueryResult(con, query).fetchone()
    return render_template('post.html',title=post[4],post=post)


@posts.route("/post/<int:post_id>/update",methods=['GET','POST'])
@is_logged_in
def update_post(post_id):
    form = PostForm()
    reader = getInstance()
    con = DBConnectivity.getConnection(reader.get('Credential', 'hostname'), reader.get('Credential', 'username'), reader.get('Credential', 'passwrod'), reader.get('Credential', 'database'))
    query = "select u.user_id,u.username,u.image_file,p.post_id,p.title,p.content,p.date_posted from user u join posts p on u.user_id=p.user_id where post_id="+str(post_id)
    post = DBConnectivity.getQueryResult(con, query).fetchone()
    if post[1] != session['username']:
        abort(403)
    if form.validate_on_submit():
        query = "update posts set title='"+form.title.data+"', content='"+form.content.data+"' where post_id="+str(post[3])
        DBConnectivity.updateDatabase(con, query)
        flash("Post has been successfully updated!","success")
        return redirect(url_for("posts.post",post_id=post[3]))
    elif request.method == 'GET':
        form.title.data=post[4]
        form.content.data = post[5]
    return render_template('create_post.html',title=post[4],legend="Update Post",post=post,form=form)


@posts.route('/delete_post/<int:post_id>',methods=['GET','POST'])
@is_logged_in
def delete_post(post_id):
    reader = getInstance()
    con = DBConnectivity.getConnection(reader.get('Credential', 'hostname'), reader.get('Credential', 'username'), reader.get('Credential', 'passwrod'), reader.get('Credential', 'database'))
    query = "delete from posts where post_id="+str(post_id)
    DBConnectivity.updateDatabase(con, query)
    flash("Your post has been successfully deleted!", "success")
    return redirect(url_for('main.home'))

flaskblog/user/routes.py
from flask import render_template,url_for,flash,redirect,request,Blueprint
from flaskblog.user.forms import RegistrationForm,LoginForm,UpdateAccountForm,ForgotPassword,ForgotPassword_OTP,ForgotPassword_Resend_OTP,Password_Change
from flaskblog import bcrypt
from functools import wraps
from Utils.ConfigReader import getInstance
from Utils.DBConnectivity import DBConnectivity
from flaskblog.user.utils import *
from Utils.GmailFactory import send_email
import random
from flaskblog import session
 
users = Blueprint('users',__name__)


#check User logged in or not
def is_logged_in(f):
    @wraps(f)
    def wrap(*args, **kwargs):
        if 'logged_in' in session:
            return f(*args,**kwargs)
        else:
            flash("Unauthorized, Please Login", "danger")
            return redirect(url_for("users.login"))      
    return wrap

#check User logged off or not
def is_logged_off(f):
    @wraps(f)
    def wrap(*args, **kwargs):
        if 'logged_in' not in session:
            return f(*args,**kwargs)
        else:
            flash("Unauthorized, Please Logout", "danger")
            return redirect(url_for("main.home"))      
    return wrap


@users.route('/register',methods=['GET','POST'])
@is_logged_off
def register():
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        username = form.username.data
        email = form.email.data
        query = "select * from user where username='"+username+"'"
        reader = getInstance()
        con = DBConnectivity.getConnection(reader.get('Credential', 'hostname'), reader.get('Credential', 'username'), reader.get('Credential', 'passwrod'), reader.get('Credential', 'database'))
        cursor = DBConnectivity.getQueryResult(con, query)
        cursor = cursor.fetchone()
        if(cursor == None):
            query = "select * from user where email='"+email+"'"
            cursor = DBConnectivity.getQueryResult(con, query)
            cursor = cursor.fetchone()
            if(cursor == None):
                query = "insert into user(username,email,password) values('"+username+"','"+email+"','"+hashed_password+"')"
                DBConnectivity.updateDatabase(con, query)
                flash(f"User has successfully registered!", "success")
                DBConnectivity.closeConnection(con)
                return redirect(url_for("users.login"))
            else:
                DBConnectivity.closeConnection(con)
                flash(f"Email has already exists!", "danger")
                return redirect(url_for("users.register"))
        else:
            DBConnectivity.closeConnection(con)
            flash(f"Username has already exists!", "danger")
            return redirect(url_for("users.register"))          
    return render_template("register.html",title = "Registration" , form = form)


@users.route('/login',methods=['GET','POST'])
@is_logged_off
def login():
    form = LoginForm()
    if form.validate_on_submit():
        reader = getInstance()
        con = DBConnectivity.getConnection(reader.get('Credential', 'hostname'), reader.get('Credential', 'username'), reader.get('Credential', 'passwrod'), reader.get('Credential', 'database'))
        query = "select * from user where Email='"+form.email.data+"'"
        cursor = DBConnectivity.getQueryResult(con, query)
        user = cursor.fetchone()
        if user != None:
            hashed_pwd = str(user[3])
            if(bcrypt.check_password_hash(hashed_pwd,form.password.data)):
                session['logged_in'] = True
                session['username'] = user[1]
                session['email'] = user[2]
                session['image_file'] = user[4]
                #flash("You have been logged in", "success")
                return redirect(url_for("users.account"))
            else:
                flash("Invalid Password!!", "danger")
                return redirect(url_for("users.login"))
            DBConnectivity.closeConnection(con)
        else:
            flash("User does not exists!", "danger")
            return redirect(url_for("users.register"))
        DBConnectivity.closeConnection(con)
    return render_template("login.html",title = "Login" , form = form)
 
 
@users.route('/account',methods=['GET','POST'])
@is_logged_in
def account():
    form=UpdateAccountForm()
    reader = getInstance()
    con = DBConnectivity.getConnection(reader.get('Credential', 'hostname'), reader.get('Credential', 'username'), reader.get('Credential', 'passwrod'), reader.get('Credential', 'database'))
    query = "select * from user where username='"+session['username']+"'"
    user = DBConnectivity.getQueryResult(con, query).fetchone()
    if form.validate_on_submit():
        query = "select * from user where username='"+form.username.data+"' and user_id <> "+str(user[0])
        result = DBConnectivity.getQueryResult(con, query).fetchone()
        if result == None:
            query = "select * from user where email='"+form.email.data+"' and user_id <> "+str(user[0])
            result = DBConnectivity.getQueryResult(con, query).fetchone()
            if result == None:
                if form.picture.data:
                    picture_file = save_picture(form.picture.data)
                    query = "UPDATE USER SET image_file='"+picture_file+"' where user_id="+str(user[0])
                    DBConnectivity.updateDatabase(con, query)
                    session['image_file'] = picture_file
                session['username'] = form.username.data
                session['email'] = form.email.data
                query = "UPDATE USER SET username='"+form.username.data+"',email='"+form.email.data+"' where user_id="+str(user[0])
                DBConnectivity.updateDatabase(con, query)
                DBConnectivity.closeConnection(con)
                flash("Account has been updated!","success")
                return redirect(url_for("users.account"))
            else:
                DBConnectivity.closeConnection(con)
                flash("Email has already exists!","danger")
                return redirect(url_for("users.account"))
        else:
            DBConnectivity.closeConnection(con)
            flash("Username has already exists!","danger")
            return redirect(url_for("users.account"))
        
    elif request.method == "GET":
        form.username.data = session['username']
        form.email.data = session['email'] 
    if(user[4] == None):
        image_file = url_for('static',filename = 'profilepics/pubg.jpg')
    else:
        image_file = url_for('static',filename = 'profilepics/'+user[4])
    DBConnectivity.closeConnection(con)
    return render_template('account.html',title ="Account",image_file=image_file,form=form)    
       
 
@users.route('/logout')
@is_logged_in
def logout():
    session.clear()
    return redirect(url_for("main.home"))


@users.route('/my_post')
@is_logged_in
def my_post():
    reader = getInstance()
    con = DBConnectivity.getConnection(reader.get('Credential', 'hostname'), reader.get('Credential', 'username'), reader.get('Credential', 'passwrod'), reader.get('Credential', 'database'))
    query = "select u.user_id,u.username,u.image_file,p.post_id,p.title,p.content,p.date_posted from user u join posts p on u.user_id=p.user_id where u.username='"+session['username']+"'"
    posts = DBConnectivity.getQueryResult(con, query).fetchall()
    return render_template("my_post.html",posts=posts)


@users.route('/forgot_password',methods=['GET','POST'])    
@is_logged_off
def forgot_password():
    form = ForgotPassword()
    if form.validate_on_submit():
        reader = getInstance()
        con = DBConnectivity.getConnection(reader.get('Credential', 'hostname'), reader.get('Credential', 'username'), reader.get('Credential', 'passwrod'), reader.get('Credential', 'database'))
        query = "select * from user where email='"+form.email.data+"'"
        result = DBConnectivity.getQueryResult(con, query).fetchone()
        if result != None:
            session['email'] = form.email.data
            OTP =  str(random.randrange(1001,10000))
            session['OTP'] = OTP
            subject = "Flask Blog Application"
            msg = OTP+"  is your One time password (OTP) for Flask Blog Application."
            send_email(subject, msg, form.email.data)
            flash("Email has been sent with OTP to given Email address","success")
            return redirect(url_for("users.forgot_password_otp"))
        else:
            flash("Email does not exists Please Sign Up","danger")
            return redirect(url_for("users.register"))
        DBConnectivity.closeConnection(con)
    return render_template('forgot_password.html',form=form)
   
 
@users.route('/forgot_password_otp',methods=['GET','POST'])    
@is_logged_off
def forgot_password_otp():
    form = ForgotPassword_OTP()
    if form.validate_on_submit():
        counter = form.otp_counter.data
        if (counter == '0'):
            session['OTP'] = None
            flash("OTP has been expired","danger")
            return redirect(url_for("users.forgot_password_otp_resend"))
        else:
            if session['OTP'] == form.otp.data:
                return redirect(url_for("users.forgot_password_change"))
            else:
                flash("OTP is incorrect","danger")
                return redirect(url_for("users.forgot_password_otp_resend"))
    elif request.method == 'GET':
        form.email.data = session['email']
    return render_template('forgot_password_otp.html',form=form)
   
@users.route('/forgot_password_otp_resend',methods=['GET','POST'])    
@is_logged_off
def forgot_password_otp_resend():
    form = ForgotPassword_Resend_OTP()
    if form.validate_on_submit():
        reader = getInstance()

flaskblog/templates/about.html
{% extends 'layout.html' %}
{% block content %}
	<h1>About Us</h1>
	<hr>
	<p>This is Flask based Blog Application</p>
{% endblock content %}

flaskblog/templates/account.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
      <div class="media">
        <img class="rounded-circle account-img" src="{{ image_file }}">
        <div class="media-body">
          <h2 class="account-heading">{{ session.username }}</h2>
          <p class="text-secondary">{{ session.email }}</p>
        </div>
      </div>
        <form method="POST" action="" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Account Info</legend>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}

                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.picture.label() }}
                    {{ form.picture(class="form-control-file") }}
                    {% if form.picture.errors %}                        
                         {% for error in form.picture.errors %}
                             <span class="text-danger">{{ error }}</span></br>
                         {% endfor %}
        			{% endif %}
        		</div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

flaskblog/templates/create_post.html
{% extends 'layout.html' %}
{% block content %}
	<div class = "content-section">
		<form method="POST" action="">
			{{ form.hidden_tag() }}
			<fieldset class="form-group">
				<legend class="border=-bottom mb-4">{{ legend }}</legend>
				<div class="form-group">
					{{ form.title.label(class="form-control-label") }}
					
					{% if form.title.errors %}
						{{ form.title(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.title.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.title(class="form-control form-control-lg") }}
					{% endif %}
				</div>
				<div class="form-group">
					{{ form.content.label(class="form-control-label") }}
					
					{% if form.content.errors %}
						{{ form.content(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.content.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.content(class="form-control form-control-lg") }}
					{% endif %}
				</div>
			</fieldset>
			<div class = "form-group">
				{{ form.submit(class="btn btn-success") }}
			</div>
		</form>
	</div>
{% endblock content %}

flaskblog/templates/forgot_password.html
{% extends 'layout.html' %}
{% block content %}
<div class = "content-section">
		<form method="POST" action="">
			{{ form.hidden_tag() }}
			<fieldset class="form-group">
				<legend class="border=-bottom mb-4">Password Change</legend>
				<div class="form-group">
					{{ form.email.label(class="form-control-label") }}
					
					{% if form.email.errors %}
						{{ form.email(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.email.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.email(class="form-control form-control-lg") }}
					{% endif %}
				</div>
			</fieldset>
			<div class = "form-group">
				{{ form.submit(class="btn btn-success") }}
			</div>
		</form>
	</div>
{% endblock content %}

flaskblog/templates/forgot_password_change.html
{% extends 'layout.html' %}
{% block content %}
	<div class = "content-section">
		<form method="POST" action="">
			{{ form.hidden_tag() }}
			<fieldset class="form-group">
				<legend class="border=-bottom mb-4">Password Change</legend>
				<div class="form-group">
					{{ form.password.label(class="form-control-label") }}
					
					{% if form.password.errors %}
						{{ form.password(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.password.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.password(class="form-control form-control-lg") }}
					{% endif %}
				</div>
				<div class="form-group">
					{{ form.confirm_password.label(class="form-control-label") }}
					
					{% if form.confirm_password.errors %}
						{{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.confirm_password.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.confirm_password(class="form-control form-control-lg") }}
					{% endif %}
				</div>
			</fieldset>
			<div class = "form-group">
				{{ form.submit(class="btn btn-success") }}
			</div>
		</form>
	</div>
{% endblock content %}

flaskblog/templates/forgot_password_otp.html
{% extends 'layout.html' %}
{% block content %}
<script type="text/javascript">
function countDown(secs,elem){
	var element = document.getElementById(elem);
	element.value = secs; 
	if(secs < 1){
		clearTimeout(timer);
		document.getElementById("statusline").innerHTML = "<span style='color: red;'>Your Timer Has been expired</span>"
			
		secs++;
	}
	
	secs--;
	var timer = setTimeout('countDown('+secs+',"'+elem+'")',1000);
}
</script>
<div class = "content-section">
		<form method="POST" action="">
			{{ form.hidden_tag() }}
			<fieldset class="form-group">
				<legend class="border=-bottom mb-4">Password Change</legend>
				<div class="form-group">
					{{ form.email.label(class="form-control-label") }}
					
					{% if form.email.errors %}
						{{ form.email(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.email.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.email(class="form-control form-control-lg") }}
					{% endif %}
				</div>
				<div class="form-group">
					{{ form.otp.label(class="form-control-label") }}
					
					{% if form.otp.errors %}
						{{ form.otp(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.otp.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.otp(class="form-control form-control-lg") }}
					{% endif %}
				</div>
				<div id = "statusline" class="">Your OTP will expire in </div>
				{{ form.otp_counter(class="col-xs-2",id="status") }}
			</fieldset>
			<table>
			<tr>
			<td>
				<div class = "form-group">
					{{ form.submit(class="btn btn-success") }}
				</div>
			</td>
			<td>
				<div class = "form-group">
						<a class="btn btn-secondary" href="/forgot_password_otp_resend">Resend</a>
				</div>
			</td>
			</tr>
			</table>		
		</form>
</div>
<script type = "text/javascript">countDown(120,"status");</script>
{% endblock content %}

flaskblog/templates/forgot_password_otp_resend.html
{% extends 'layout.html' %}
{% block content %}
<div class = "content-section">
		<form method="POST" action="">
			{{ form.hidden_tag() }}
			<fieldset class="form-group">
				<legend class="border=-bottom mb-4">Password Change</legend>
				<div class="form-group">
					{{ form.email.label(class="form-control-label") }}
					
					{% if form.email.errors %}
						{{ form.email(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.email.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.email(class="form-control form-control-lg") }}
					{% endif %}
				</div>
			</fieldset>
			<div class = "form-group">
				{{ form.submit(class="btn btn-success") }}
			</div>
		</form>
	</div>
{% endblock content %}

flaskblog/templates/home.html
{% extends 'layout.html' %}
{% block content %}
	{% for post in posts %}
		<article class="media content-section">
		  <img class="rounded-circle article-img" src="{{ url_for('static',filename='profilepics/'+post[2]) }}">
		  <div class="media-body">
		    <div class="article-metadata">
		      <a class="mr-2" href="#">{{ post[1] }}</a>
		      <small class="text-muted">{{ post[6].strftime('%Y-%m-%d') }}</small>
		    </div>
		    <h2><a class="article-title" href="post/{{ post[3] }}">{{ post[4] }}</a></h2>
		    <p class="article-content">{{ post[5] }}</p>
		  </div>
		</article>
	{% endfor %}
{% endblock content %}

flaskblog/templates/layout.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
	    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	
	    <!-- Bootstrap CSS -->
	    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
	
		<link rel="stylesheet" type="text/css" href ="{{ url_for('static' ,filename = 'main.css')}}">
		{% if title %}
        	<title>Flask Blog - {{ title }}</title>
    	{% else %}
        	<title>Flask Blog</title>
    	{% endif %}
		
	</head>
	<body>
		{% include "includes/navigation.html" %}
		<main role="main" class="container">
		  <div class="row">
		    <div class="col-md-8">
			  {% include "includes/flashmessage.html" %}
		      {% block content %}{% endblock %}
		    </div>
		    <div class="col-md-4">
		      <div class="content-section">
		        <h3>Our Sidebar</h3>
		        <p class='text-muted'>You can put any information here you'd like.
		          <ul class="list-group">
		            <li class="list-group-item list-group-item-light">Latest Posts</li>
		            <li class="list-group-item list-group-item-light">Announcements</li>
		            <li class="list-group-item list-group-item-light">Calendars</li>
		            <li class="list-group-item list-group-item-light">etc</li>
		          </ul>
		        </p>
		      </div>
		    </div>
		  </div>
		</main>
		
		<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
	    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
	    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
	</body>
</html>

flaskblog/templates/login.html
{% extends 'layout.html' %}
{% block content %}
	<div class = "content-section">
		<form method="POST" action="">
			{{ form.hidden_tag() }}
			<fieldset class="form-group">
				<legend class="border=-bottom mb-4">Log In</legend>
				<div class="form-group">
					{{ form.email.label(class="form-control-label") }}
					
					{% if form.email.errors %}
						{{ form.email(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.email.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.email(class="form-control form-control-lg") }}
					{% endif %}
				</div>
				<div class="form-group">
					{{ form.password.label(class="form-control-label") }}
					
					{% if form.password.errors %}
						{{ form.password(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.password.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.password(class="form-control form-control-lg") }}
					{% endif %}
				</div>
				<div class="form-check">
					{{ form.remember(class="form-check-input") }}
					{{ form.remember.label(class="form-check-label")}}
				</div>
			</fieldset>
			<div class = "form-group">
				{{ form.submit(class="btn btn-success") }}
				<small class="text-muted ml-2">
					<a href="{{ url_for('users.forgot_password') }}">Forgot Password?</a>
				</small>
			</div>

		</form>
		
		<div class="border-top pt-3">
			<small class="text-muted">
				Need An Account? <a class="ml-2" href="{{ url_for('users.register') }}">Sign Up</a>
			</small>
		</div>
	</div>
{% endblock content %}

flaskblog/templates/my_post.html
{% extends 'layout.html' %}
{% block content %}
	{% for post in posts %}
		<article class="media content-section">
		  <img class="rounded-circle article-img" src="{{ url_for('static',filename='profilepics/'+post[2]) }}">
		  <div class="media-body">
		    <div class="article-metadata">
		      <a class="mr-2" href="#">{{ post[1] }}</a>
		      <small class="text-muted">{{ post[6].strftime('%Y-%m-%d') }}</small>
		    </div>
		    <h2><a class="article-title" href="post/{{ post[3] }}">{{ post[4] }}</a></h2>
		    <p class="article-content">{{ post[5] }}</p>
		  </div>
		</article>
	{% endfor %}
{% endblock content %}

flaskblog/templates/post.html
{% extends 'layout.html' %}
{% block content %}
	<article class="media content-section">
	  <img class="rounded-circle article-img" src="{{ url_for('static',filename='profilepics/'+post[2]) }}">
	  <div class="media-body">
	    <div class="article-metadata">
	      <a class="mr-2" href="#">{{ post[1] }}</a>
	      <small class="text-muted">{{ post[6].strftime('%Y-%m-%d') }}</small>
	      {% if session.username == post[1] %}
	  		  <a class="btn btn-secondary btn-sm m-1" href="/post/{{post[3]}}/update">Update</a>
	  		  <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
	      {% endif %}
	    </div>
	    <h2 class="article-title">{{ post[4] }}</h2>
	    <p class="article-content">{{ post[5] }}</p>
	  </div>
	</article>
	<!-- Modal -->
	  <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
	    <div class="modal-dialog" role="document">
	      <div class="modal-content">
	        <div class="modal-header">
	          <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
	          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
	            <span aria-hidden="true">&times;</span>
	          </button>
	        </div>
	        <div class="modal-footer">
	          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
	          <form action="{{ url_for('posts.delete_post', post_id=post[3]) }}" method="POST">
	            <input class="btn btn-danger" type="submit" value="Delete">
	          </form>
	        </div>
	      </div>
	    </div>
	  </div>
{% endblock content %}